### ISSUE TITLE
Starting Point

### ISSUE THREAD

**Issue by blaggacao** [odoo-colombia/provisioning#8]
Hello Christian, could this be a starting point to get it to work properly and in a best practivce way (including things like selecting mirrors and such stuff, to help peoples live when the don't sit right on a backbone)

https://github.com/odoo-colombia/provisioning/tree/master/vagrant-ubuntu-anisble

**Comment by ovnicraft** [comment]
@blaggacao you get the last comment from here: https://gist.github.com/slickplaid/5557321#gistcomment-1550753
